### PR TITLE
Depend on rpi-make-boot-image package/script

### PR DESCRIPTION
**Pull request by roliver-rpi**
This addresses https://github.com/raspberrypi/pi-gen-micro/issues/21

### CODE REVIEW

**Review by tdewey-rpi — APPROVED** [review]

**Comment by tdewey-rpi** [comment]
Is this package ready to go in the repo?

**Comment by roliver-rpi** [comment]
We should bump the version number and update the changelog before putting this in the repo.

**Comment by tdewey-rpi** [comment]
> We should bump the version number and update the changelog before putting this in the repo.

Not this package, but the new one you're going to depend on.

**Comment by roliver-rpi** [comment]
rpi-make-boot-image is already in our repo under http://archive.raspberrypi.com/debian/pool/main/r/rpiboot/

**Pull request merged**
